// Actions
export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA'
export const FETCH_STATIC_DATA = 'FETCH_STATIC_DATA'
export const FETCH_INSURANCE_LIST = 'FETCH_INSURANCE_LIST'
export const FETCH_RELATED_QUESTIONS = 'FETCH_RELATED_QUESTIONS'
export const FETCH_RELATED_BLOGS = 'FETCH_RELATED_BLOGS'
export const FETCH_PROMOTION_PRODUCTS = 'FETCH_PROMOTION_PRODUCTS'
export const UPDATE_INSURANCE_PRODUCT_FEE = 'UPDATE_INSURANCE_PRODUCT_FEE'

// Mutations
export const UPDATE_STATIC_DATA = 'UPDATE_STATIC_DATA'
export const UPDATE_INSURANCE_LIST_DATA = 'UPDATE_INSURANCE_LIST_DATA'
export const UPDATE_INSURANCE_LIST_META = 'UPDATE_INSURANCE_LIST_META'
export const UPDATE_INSURANCE_LIST_PRODUCT_FEE =
  'UPDATE_INSURANCE_LIST_PRODUCT_FEE'
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE'
export const UPDATE_RELATED_QUESTIONS = 'UPDATE_RELATED_QUESTIONS'
export const UPDATE_RELATED_BLOGS = 'UPDATE_RELATED_BLOGS'
export const UPDATE_PROMOTION_PRODUCTS = 'UPDATE_PROMOTION_PRODUCTS'
export const UPDATE_PROMOTION_PRODUCT_FEE = 'UPDATE_PROMOTION_PRODUCT_FEE'
