// Actions
export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA'
export const FETCH_STATIC_DATA = 'FETCH_STATIC_DATA'
export const FETCH_RELATED_QUESTIONS = 'FETCH_RELATED_QUESTIONS'
export const FETCH_RELATED_BLOGS = 'FETCH_RELATED_BLOGS'
export const FETCH_PROMOTION_PRODUCTS = 'FETCH_PROMOTION_PRODUCTS'

// Mutations
export const UPDATE_STATIC_DATA = 'UPDATE_QUESTION_LIST_DATA'
export const UPDATE_RELATED_QUESTIONS = 'UPDATE_RELATED_QUESTIONS'
export const UPDATE_RELATED_BLOGS = 'UPDATE_RELATED_BLOGS'
export const UPDATE_PROMOTION_PRODUCTS = 'UPDATE_PROMOTION_PRODUCTS'

// Both
