// Actions
export const FETCH_LEADER_BOARD = 'FETCH_LEADER_BOARD'

// Mutations
export const UPDATE_LEADER_BOARD = 'UPDATE_LEADER_BOARD'
export const UPDATE_FETCHING_STATUS = 'UPDATE_FETCHING_STATUS'
