// Actions
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'

// Mutations
export const UPDATE_FEE = 'UPDATE_FEE'
export const UPDATE_SINGLE_PRODUCT = 'UPDATE_SINGLE_PRODUCT'
export const UPDATE_SELECTED_CASE_INDEX = 'UPDATE_SELECTED_CASE_INDEX'
export const UPDATE_INSURED_AMOUNT = 'UPDATE_INSURED_AMOUNT'
