// Actions
export const FETCH_PRODUCT = 'FETCH_PRODUCT'

// Mutations
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_ID = 'UPDATE_PRODUCT_ID'
export const UPDATE_PREMIUM_QUERY = 'UPDATE_PREMIUM_QUERY'
export const UPDATE_FEE = 'UPDATE_FEE'
