// Actions
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_FEE = 'FETCH_PRODUCT_FEE'

// Mutations
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_ID = 'UPDATE_PRODUCT_ID'
export const UPDATE_PREMIUM_QUERY = 'UPDATE_PREMIUM_QUERY'
export const UPDATE_FEE = 'UPDATE_FEE'
export const CLEAR_FEE = 'CLEAR_FEE'
export const UPDATE_COVERAGE = 'UPDATE_COVERAGE'

// Both
export const UPDATE_PREMIUM_QUERY_KEY = 'UPDATE_PREMIUM_QUERY_KEY'
export const UPDATE_PREMIUM_QUERY_VALIDATE = 'UPDATE_PREMIUM_QUERY_VALIDATE'
