// Actions
export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA'
export const FETCH_POPULAR_QUESTIONS = 'FETCH_POPULAR_QUESTIONS'
export const FETCH_POPULAR_BLOGS = 'FETCH_POPULAR_BLOGS'

// Mutations
export const UPDATE_POPULAR_QUESTIONS = 'UPDATE_POPULAR_QUESTIONS'
export const UPDATE_POPULAR_BLOGS = 'UPDATE_POPULAR_BLOGS'

// Both
