// Actions
export const FETCH_PAGE_DATA = 'FETCH_PAGE_DATA'
export const FETCH_QUESTION_LIST = 'FETCH_QUESTION_LIST'
export const FETCH_POPULAR_QUESTIONS = 'FETCH_POPULAR_QUESTIONS'
export const FETCH_POPULAR_BLOGS = 'FETCH_POPULAR_BLOGS'

// Mutations
export const UPDATE_QUESTION_LIST_DATA = 'UPDATE_QUESTION_LIST_DATA'
export const UPDATE_QUESTION_LIST_META = 'UPDATE_QUESTION_LIST_META'
export const UPDATE_POPULAR_QUESTIONS = 'UPDATE_POPULAR_QUESTIONS'
export const UPDATE_POPULAR_BLOGS = 'UPDATE_POPULAR_BLOGS'
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE'
export const UPDATE_CURRENT_SORT = 'UPDATE_CURRENT_SORT'

// Both
