// Actions
export const FETCH_QUESTION_DATA = 'FETCH_QUESTION_DATA'
export const FETCH_ANSWER_DATA = 'FETCH_ANSWER_DATA'
export const FETCH_QUESTION_PERSONALIZE_DATA = 'FETCH_QUESTION_PERSONALIZE_DATA'
export const FETCH_ANSWER_PERSONALIZE_DATA = 'FETCH_ANSWER_PERSONALIZE_DATA'
export const HIGHLIGHT_BEST_ANSWER = 'HIGHLIGHT_BEST_ANSWER'
export const FOLLOW_QUESTION = 'FOLLOW_QUESTION'
export const UNFOLLOW_QUESTION = 'UNFOLLOW_QUESTION'
export const SET_QUESTION_BEST_ANSWER = 'SET_QUESTION_BEST_ANSWER'
export const UNSET_QUESTION_BEST_ANSWER = 'UNSET_QUESTION_BEST_ANSWER'

// Mutations
export const UPDATE_QUESTION_DATA = 'UPDATE_QUESTION_DATA'
export const UPDATE_ANSWER_DATA = 'UPDATE_ANSWER_DATA'
export const UPDATE_TOP_ANSWER_ORDER = 'UPDATE_TOP_ANSWER_ORDER'
export const UPDATE_QUESTION_PERSONALIZE_DATA =
  'UPDATE_QUESTION_PERSONALIZE_DATA'
export const UPDATE_ANSWER_PERSONALIZE_DATA = 'UPDATE_ANSWER_PERSONALIZE_DATA'
export const UPDATE_QUESTION_FOLLOW_STATE = 'UPDATE_QUESTION_FOLLOW_STATE'
export const UPDATE_QUESTION_BEST_ANSWER = 'UPDATE_QUESTION_BEST_ANSWER'
