// Actions
export const FETCH_QUESTION_DATA = 'FETCH_QUESTION_DATA'
export const FETCH_ANSWER_DATA = 'FETCH_ANSWER_DATA'

// Mutations
export const UPDATE_QUESTION_DATA = 'UPDATE_QUESTION_DATA'
export const UPDATE_ANSWER_DATA = 'UPDATE_ANSWER_DATA'
