// Login panel

// Actions
export const OPEN_LOGIN_PANEL = 'OPEN_LOGIN_PANEL'
export const CLOSE_LOGIN_PANEL = 'CLOSE_LOGIN_PANEL'
export const NAVIGATE_LOGIN_PANEL = 'NAVIGATE_LOGIN_PANEL'

// Mutations
export const UPDATE_LOGIN_PANEL_STATUS = 'UPDATE_LOGIN_PANEL_STATUS'
export const UPDATE_USER_AGENT = 'UPDATE_USER_AGENT'

// Both
export const UPDATE_AFTER_LOGIN_EVENT = 'UPDATE_AFTER_LOGIN_EVENT'
export const UPDATE_AFTER_CLOSE_LOGIN_PANEL_EVENT =
  'UPDATE_AFTER_CLOSE_LOGIN_PANEL_EVENT'

// Global dialog popup
// Actions
export const OPEN_GLOBAL_DIALOG = 'OPEN_GLOBAL_DIALOG'
export const CLOSE_GLOBAL_DIALOG = 'CLOSE_GLOBAL_DIALOG'
export const UPDATE_GLOBAL_DIALOG = 'UPDATE_GLOBAL_DIALOG'

// Mutations
export const UPDATE_GLOBAL_DIALOG_DISPLAY = 'UPDATE_GLOBAL_DIALOG_DISPLAY'
export const UPDATE_GLOBAL_DIALOG_CONTENT = 'UPDATE_GLOBAL_DIALOG_CONTENT'

// Error page custom CTA update
// Actions
export const ADD_CUSTOM_ERROR_PAGE_CTA = 'ADD_CUSTOM_ERROR_PAGE_CTA'
export const REMOVE_CUSTOM_ERROR_PAGE_CTA = 'REMOVE_CUSTOM_ERROR_PAGE_CTA'

// Mutations
export const UPDATE_ERROR_PAGE_CTA = 'UPDATE_ERROR_PAGE_CTA'
