apiVersion: apps/v1
kind: Deployment
metadata:
  name: my83-f2e-app-staging-deployment
  namespace: my83-f2e
spec:
  selector:
    matchLabels:
      app: my83-f2e-app
      env: staging
  template:
    metadata:
      name: my83-f2e-pod
      labels:
        app: my83-f2e-app
        env: staging
      namespace: my83-f2e
    spec:
      containers:
        - name: my83-f2e
          image: asia.gcr.io/my83-253509/my83-f2e:FRONT_APP_IMAGE_TAG
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: my83-f2e-app-env-staging
          ports:
            - name: nuxt-port
              containerPort: 3000
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "600Mi"
          readinessProbe:
            httpGet:
              path: /ping
              port: nuxt-port
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: nuxt-port
            initialDelaySeconds: 15
            periodSeconds: 20
