// Actions
export const FETCH_HEADER_NAV_DATA = 'FETCH_HEADER_NAV_DATA'
export const FETCH_HEADER_PERSONALIZED_DATA = 'FETCH_HEADER_PERSONALIZED_DATA'

// Mutations
export const UPDATE_HEADER_NAV_DATA = 'UPDATE_HEADER_NAV_DATA'
export const UPDATE_HEADER_PERSONALIZED_DATA = 'UPDATE_HEADER_PERSONALIZED_DATA'
export const UPDATE_HEADER_ANNOUNCEMENT = 'UPDATE_HEADER_ANNOUNCEMENT'
